version: '3.4'

services: 
  nginx-proxy:
    image: nginx
    volumes: 
      - ./nginx/servers.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
  app1:
    image: nginx
    volumes: 
      - ./nginx/app1.html:/usr/share/nginx/html/index.html
    ports: 
      - 80
  app2:
    image: nginx
    volumes: 
      - ./nginx/app2.html:/usr/share/nginx/html/index.html
    ports: 
      - 80